# Global Relayer configuration
global:
  privateKey: ''                        # The privateKey of the account that will be submitting the packet relays
  logLevel: 'info'
  blockDelay: 5                         # Delay with which to process the chain blocks

  getter:
    interval: 5000                      # Interval at which to poll the chains RPCs for new events
    maxBlocks: 1000                     # Maximum number of blocks to query in a single call

  submitter:
    enabled: true
    newOrdersDelay: 1000                # Time to wait before processing new 'submission' orders
    retryInterval: 30000                # Time to wait before retrying a failed transaction
    processingInterval: 100             # Throttle for the Submitter main 'run' loop
    maxTries: 3                         # Maximum tries for a transaction
    maxPendingTransactions: 50          # Maximum number of transactions within the 'submit' pipeline.
    confirmations: 1                    # Number of confirmations to deem that a transaction has been mined
    confirmationTimeout: 90000          # Timeout for a transaction to confirm

    lowBalanceWarning:                  # Balance below which a 'low balance' warning is emitted.
      '1000000000000000000'
    balanceUpdateInterval: 50           # Number of transactions after which to update the Relayer balance from the rpc.

    # Gas properties
    gasLimitBuffer:                     # Extra gasLimit buffer. Customizable per AMB.
      default: 10000
      mock: 50000

    # EIP-1559 Transactions
    maxFeePerGas: '200000000000'        # 'maxFeePerGas' set for all transactions (for chains that support eip-1559)

    maxAllowedPriorityFeePerGas:        # Upper bound to the 'maxPriorityFeePerGas' set on transactions (for chains that support eip-1559)
      '100000000000'
    maxPriorityFeeAdjustmentFactor:     # Decimal factor used to adjust the 'maxPriorityFeePerGas' returned by 'getFeeData()'.
      1.05                              # The resulting value is set as the 'maxPriorityFeePerGas' property of the transaction
                                        # if it is smaller than the configuration property 'maxAllowedPriorityFeePerGas' (if set).

    # Legacy Transactions
    maxAllowedGasPrice: '200000000000'  # Upper bound to the 'gasPrice' set on transactions (for chains that do not support eip-1559)
    gasPriceAdjustmentFactor: 1.05      # Decimal factor used to adjust the 'gasPrice' returned by 'getFeeData()'. The resulting
                                        # value is set as the 'gasPrice' property of the transaction if it is smaller than the
                                        # configuration property 'maxAllowedGasPrice' (if set).

    # All Transactions
    priorityAdjustmentFactor: 1.2       # Decimal factor used to adjust **all** the gas prices (including 'maxFeePerGas') for
                                        # priority transactions.

  persister:
    enabled: false
    postgresString: 'postgresql://username:password@location/database?sslmode=require'

# AMBs configuration
ambs:
  # Mock is used for internal testnets. For production it should never be used.
  - name: mock
    enabled: false                      # Defaults to 'true' if the key is missing
    incentivesAddress: '0x0000000000000000000000000000000000000000'
    privateKey: ''

  # While we can't relay packages for Polymer, we to still collect the packages for the underwriter to work.
  - name: polymer

  - name: wormhole
    isTestnet: true

# Chain configuration
chains:
  - chainId: 80001
    name: 'Mumbai'
    rpc: 'https://polygon-mumbai-pokt.nodies.app'

    blockDelay: 2
    # startingBlock   # The block number at which to start Relaying (not all AMB collectors may support this property)
    # stoppingBlock   # The block number at which to stop Relaying (not all AMB collectors may support this property)

    # Overrides
    getter:
      interval: 3000
    submitter:
      retryInterval: 3000

    # AMB configuration
    wormhole:
      wormholeChainId: 5

  - chainId: 11155111
    name: 'Sepolia'
    rpc: 'https://eth-sepolia-public.unifra.io'
    wormhole:
      wormholeChainId: 10002
      incentivesAddress: '0x45C140Dd2526E4bfD1c2A5Bb0Aa6aA1DB00b1744'
      bridgeAddress: '0x4a8bc80Ed5a4067f1CCf107057b8270E0cC11A78'

  - chainId: 421614
    name: 'Arbitrum Sepolia'
    rpc: 'https://sepolia-rollup.arbitrum.io/rpc' # NOTE: This rpc errors easily with a 'requests rate too high' error
    blockDelay: 5
    getter:
      interval: 2000
      maxBlocks: 5000
    wormhole:
      wormholeChainId: 10003
      incentivesAddress: '0xdF25f1BdE09Cee5ac1e6ef8dFA7113addBd58B28'
      bridgeAddress: '0x6b9C8671cdDC8dEab9c719bB87cBd3e782bA6a35'

  - chainId: 11155420
    name: 'OP Sepolia'
    rpc: 'https://sepolia.optimism.io'
    wormhole:
      wormholeChainId: 10005
      incentivesAddress: '0xbDFD9163d8Cee1368698B023369f9A5Fd319A40F'
      bridgeAddress: '0x31377888146f3253211EFEf5c676D41ECe7D58Fe'
    polymer:
      incentivesAddress: '0x62e27C0bD89D7AC599Df8765cDEe0183A34A9929'
      bridgeAddress: '0x58f1863F75c9Db1c7266dC3d7b43832b58f35e83'

  - chainId: 84532
    name: 'Base Sepolia'
    rpc: 'https://rpc.notadegen.com/base/sepolia'
    polymer:
      incentivesAddress: '0x147d414F1964c94c4Ac7422aC148aBddb4BEdC82'
      bridgeAddress: '0xfC1d3E02e00e0077628e8Cc9edb6812F95Db05dC'
